### PR TITLE
when use it in tabs component it display initialization status

### PR DESCRIPTION
**Pull request by quanzhiyuan**
1. i create a component use number-clip and use element-ui tabs in my project。
2. change to other tab and wait for number-clip component which is call setInterval execute background。 
3. change back to the tab contain number-clip component  and it will display 
WX20191021-093751@2x

i write a demo here https://codesandbox.io/embed/vue-template-dqzc1?fontsize=14

### CODE REVIEW

**Comment by gaoryrt** [comment]
1. Describe in English, so that might help more people.
2. I use [gitmoji](https://github.com/carloscuesta/gitmoji-cli) for a better-looking commit.
3. Seems like https://github.com/gaoryrt/number-flip/issues/13 happens again.

**Comment by gaoryrt** [comment]
@quanzhiyuan I added a `keep-alive` here:
image
It seems the flip numbers worked normally, but errors in console still there.
Any thoughts?

**Comment by gaoryrt** [comment]
Since https://github.com/gaoryrt/number-flip/issues/22 could be solved by a setting of vue, closed this pr and #22.

**Comment by quanzhiyuan** [comment]
> @quanzhiyuan I added a `keep-alive` here:
>  @image
> It seems the flip numbers worked normally, but errors in console still there.
> Any thoughts?

it does not work ,when you change out the tab "配置管理"，you must wait a moment 。and then change back 。the follow gif is run the code which you add keep-alive。(sorry for my English )
屏幕录制2019-10-31下午3 22 47

**Pull request closed without merging**
